export const CHAIN_NAME = 'lumera'
// export const CHAIN_NAME = 'lumeratestnet'
// export const REST_AI_URL = 'https://lcd.lumera.io';
export const REST_AI_URL = 'https://lcd.testnet.lumera.io';
export const DENOM = 'ulumera';
// export const RPC_ENDPOINT = "https://rpc.lumera.io"
export const RPC_ENDPOINT = "https://rpc.testnet.lumera.io"
// export const CHAIN_ID = 'lumera-mainnet-1';
export const CHAIN_ID = 'lumera-testnet-2';